# Week 2 - Mental Health Data Analysis
## Topics covered: DataFrames, exploration, data cleaning

In [1]:
import pandas as pd
import numpy as np

data = {
    "age": [25, 32, 28, 45, 23, 36, 29, 41, 27, 33],
    "gender": ["Male", "Female", "Female", "Male", "Non-binary",
               "Female", "Male", "Female", "Male", "Female"],
    "treatment": ["Yes", "No", "Yes", "Yes", "No",
                  "Yes", "No", "Yes", "No", "Yes"],
    "work_interfere": ["Often", "Rarely", "Often", "Sometimes", "Rarely",
                       "Sometimes", "Rarely", "Often", "Never", "Sometimes"],
    "mental_health_consequence": ["Yes", "No", "Maybe", "No", "Yes",
                                  "Maybe", "No", "Yes", "No", "Maybe"]
}

df = pd.DataFrame(data)

print("Dataset loaded!")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Dataset loaded!
Rows: 10
Columns: 5

In [2]:
df.head()

   age      gender treatment work_interfere mental_health_consequence
0   25        Male       Yes          Often                       Yes
1   32      Female        No         Rarely                        No
2   28      Female       Yes          Often                     Maybe
3   45        Male       Yes      Sometimes                        No
4   23  Non-binary        No         Rarely                       Yes

In [3]:
df.tail()

   age  gender treatment work_interfere mental_health_consequence
5   36  Female       Yes      Sometimes                     Maybe
6   29    Male        No         Rarely                        No
7   41  Female       Yes          Often                       Yes
8   27    Male        No          Never                        No
9   33  Female       Yes      Sometimes                     Maybe

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        10 non-null     int64
 1   gender                     10 non-null     str
 2   treatment                  10 non-null     str
 3   work_interfere             10 non-null     str
 4   mental_health_consequence  10 non-null     str
dtypes: int64(1), str(4)
memory usage: 532.0 bytes

In [5]:
df.describe()

            age
count  10.00000
mean   31.90000
std     7.04667
min    23.00000
25%    27.25000
50%    30.50000
75%    35.25000
max    45.00000

In [6]:
df["treatment"].value_counts()

treatment
Yes    6
No     4
Name: count, dtype: int64

In [7]:
df["gender"].value_counts()

gender
Female        5
Male          4
Non-binary    1
Name: count, dtype: int64

In [8]:
df["work_interfere"].value_counts()

work_interfere
Often        3
Rarely       3
Sometimes    3
Never        1
Name: count, dtype: int64

In [9]:
df["gender"].value_counts()

gender
Female        5
Male          4
Non-binary    1
Name: count, dtype: int64

In [13]:
print("Gender breakdown:")
print(df["gender"].value_counts())
print()
print("Work interference breakdown:")
print(df["work_interfere"].value_counts())

Gender breakdown:
gender
Female        5
Male          4
Non-binary    1
Name: count, dtype: int64

Work interference breakdown:
work_interfere
Often        3
Rarely       3
Sometimes    3
Never        1
Name: count, dtype: int64

In [14]:
df.groupby("work_interfere")["treatment"].value_counts()

work_interfere  treatment
Never           No           1
Often           Yes          3
Rarely          No           3
Sometimes       Yes          3
Name: count, dtype: int64

In [15]:
df.groupby("gender")["treatment"].value_counts()

gender      treatment
Female      Yes          4
            No           1
Male        Yes          2
            No           2
Non-binary  No           1
Name: count, dtype: int64

In [16]:
messy_data = {
    "age": [25, 32, None, 45, 23, 36, 29, None, 27, 33],
    "gender": ["Male", "female", "Female", "MALE", "Non-binary",
               "Female", "male", "Female", "Male", "Female"],
    "treatment": ["Yes", "No", "Yes", "Yes", "No",
                  "Yes", "No", "Yes", "No", "Yes"]
}

df_messy = pd.DataFrame(messy_data)
print(df_messy)

    age      gender treatment
0  25.0        Male       Yes
1  32.0      female        No
2   NaN      Female       Yes
3  45.0        MALE       Yes
4  23.0  Non-binary        No
5  36.0      Female       Yes
6  29.0        male        No
7   NaN      Female       Yes
8  27.0        Male        No
9  33.0      Female       Yes

In [17]:
df_messy.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        8 non-null      float64
 1   gender     10 non-null     str
 2   treatment  10 non-null     str
dtypes: float64(1), str(2)
memory usage: 372.0 bytes

In [19]:
print("Before cleaning:")
print(df_messy["age"].isnull().sum(), "missing values in age")

df_messy["age"] = df_messy["age"].fillna(df_messy["age"].mean())

print("After cleaning:")
print(df_messy["age"].isnull().sum(), "missing values in age")

Before cleaning:
2 missing values in age
After cleaning:
0 missing values in age

In [20]:
print("Before cleaning:")
print(df_messy["gender"].value_counts())

df_messy["gender"] = df_messy["gender"].str.lower()

print("\nAfter cleaning:")
print(df_messy["gender"].value_counts())

Before cleaning:
gender
Female        4
Male          2
female        1
MALE          1
Non-binary    1
male          1
Name: count, dtype: int64

After cleaning:
gender
female        5
male          4
non-binary    1
Name: count, dtype: int64

In [21]:
df_messy.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        10 non-null     float64
 1   gender     10 non-null     str
 2   treatment  10 non-null     str
dtypes: float64(1), str(2)
memory usage: 372.0 bytes

In [22]:
df_messy["age"] = df_messy["age"].astype(int)

In [23]:
df_messy.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        10 non-null     int64
 1   gender     10 non-null     str
 2   treatment  10 non-null     str
dtypes: int64(1), str(2)
memory usage: 372.0 bytes

In [24]:
df["gender"].value_counts
df["work_interfere"].value_counts()

work_interfere
Often        3
Rarely       3
Sometimes    3
Never        1
Name: count, dtype: int64